# Start run without graph and settings

POST http://localhost:5001/testyx/us-central1/processBlocksToPaths
Content-Type: application/json

{
  "event": {
    "session_variables": {
      "x-hasura-role": "user",
      "x-hasura-user-id": "f0DF3YnYkddQWZaIaPo9ximrbgq1"
    },
    "op": "INSERT",
    "data": {
      "old": null,
      "new": {
        "graph": null,
        "settings": null,
        "finished_at": null,
        "run_by_user": 1,
        "project_id": 1,
        "id": 97,
        "started_at": "2020-06-23T13:19:32.726422+00:00"
      }
    }
  },
  "created_at": "2020-06-23T13:19:32.726422Z",
  "id": "53009dd8-71b9-43a9-8ac0-db1bc79ccfa9",
  "delivery_info": {
    "max_retries": 0,
    "current_retry": 0
  },
  "trigger": {
    "name": "run_project"
  },
  "table": {
    "schema": "public",
    "name": "run"
  }
}

### Start run with custom settings

POST http://localhost:5001/testyx/us-central1/processBlocksToPaths
Content-Type: application/json

{
  "event": {
    "session_variables": {
      "x-hasura-role": "user",
      "x-hasura-user-id": "SC3HZhk4mmSRrCCfhcJAwSNwZmL2"
    },
    "op": "INSERT",
    "data": {
      "old": null,
      "new": {
        "graph": null,
        "settings": {"resolutions":[{"width":1920,"height":1080}]},
        "finished_at": null,
        "run_by_user": 1,
        "project_id": 3,
        "id": 87,
        "started_at": "2020-06-17T14:32:19.133787+00:00"
      }
    }
  },
  "created_at": "2020-06-17T14:32:19.133787Z",
  "id": "c863a5f8-0aae-4df6-ac23-cdfe08c5a0b4",
  "delivery_info": {
    "max_retries": 0,
    "current_retry": 0
  },
  "trigger": {
    "name": "run_project"
  },
  "table": {
    "schema": "public",
    "name": "run"
  }
}